defaults: &defaults
  slackbotsy:
    channel: '#default'
    name: 'botsy'
    incoming_webhook: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'
    outgoing_token: 'secret'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults